FROM hubberonline/base

# Install xdebug
RUN pecl install xdebug
RUN docker-php-ext-enable xdebug
RUN echo "error_reporting = E_ALL" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
RUN echo "display_startup_errors = On" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
RUN echo "display_errors = On" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
RUN echo "xdebug.remote_enable=1" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
RUN echo "xdebug.remote_connect_back=1" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
RUN echo "xdebug.idekey=\"PHPSTORM\"" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
RUN echo "xdebug.remote_port=9001" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
RUN echo "xdebug.serverName=hubber-online" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
RUN echo "xdebug.extended_info = 1" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini


# Copy the project
COPY . /var/www/

# Set workdir
WORKDIR /var/www/

# Run NPM install
RUN /usr/bin/npm install -g gulp \
    && /usr/bin/npm install -g \
    && npm link gulp

# Run Composer install
RUN mkdir -p /var/www/vendor \
    && cd /var/www/ \
#    && composer config --global --auth github-oauth.github.com PUT_YOUR_TOKEN_HERE\
    && composer global require "fxp/composer-asset-plugin:*" --no-plugins\
    && composer install --no-suggest --no-progress 2>&1

# Add manual php-fpm config
COPY www.conf /usr/local/etc/php-fpm.d/www.conf

# Add entrypoint
ADD start.sh .
RUN chmod +x start.sh

# Run main command
CMD ["/bin/bash", "start.sh"]